openapi: "3.0.3"
info:
  title: "CountdownDays API"
  description: "CountdownDays API"
  version: "1.0.0"
servers:
- url: "https://CountdownDays"
paths:
  /user:
    post:
      description: "add user"
      requestBody:
        content:
          '*/*':
            schema:
              $ref: "#/components/schemas/AddUserRequest"
        required: true
  /user/{id}:
    get:
      description: "get user public information"
      parameters:
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "400":
          description: "Bad Request"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Invalid id"
                Example#2:
                  value: "Missing or malformed id"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/UserResponse"
        "404":
          description: "Not Found"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: ""
components:
  schemas:
    AddUserRequest:
      type: "object"
      properties:
        telegramId:
          type: "integer"
          format: "int32"
        username:
          type: "string"
        name:
          type: "string"
      required:
      - "username"
      - "name"
    UserResponse:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        username:
          type: "string"
        name:
          type: "string"
      required:
      - "username"
      - "name"